version: '3.8'

services:
  database:
    image: postgres:latest
    hostname: postgresdb
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB="${POSTGRES_DB}"
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgresdb:
